name: Build on Ubuntu

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest
        uses: actions-rs/toolchain@v1
        with:
            toolchain: latest
            override: true
            components: rustfmt, clippy

      - name: Build
        run: cargo build --release

      - name: LS
        run: cd target/release && ls

      - name: Add to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: exec
          path: target/release/tao-test